### ISSUE TITLE
ข้อมูล ICD10 บน Database

### ISSUE THREAD

**Issue by lionants02** [ffc-nectec/api#18]
บน Database ให้ใส่ข้อมูล ICD10 ไว้เลย ไม่ต้องขึ้นกับ JHCISDB

**Comment by porntipa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [insert เยี่ยมบ้าน](https://trello.com/c/7pSXqiFT/21-insert-%E0%B9%80%E0%B8%A2%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A1%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99)
