### ISSUE TITLE
timestamp POST แล้ว Response คนละ format

### ISSUE THREAD

**Issue by porntipa** [ffc-nectec/api#7]
POST  `2018-06-28T14:19:29.645+07:00` ไป
แต่ Response เป็น  `2018-06-28T07:19:29.645Z`

**Comment by piruin** [comment]
Timezone หายหลังจาก Query ค่ากลับจาก DB

แต่ยังไม่มีปัญหาอะไรกับระบบ เนื่องจากยังใช้เฉพาะในไทย
