### ISSUE TITLE
Register User ไม่สำเร็จ

### ISSUE THREAD

**Issue by porntipa** [ffc-nectec/api#9]
Response status 500

**Comment by piruin** [comment]
ขอรายละเอียดเพิ่ม

**Comment by porntipa** [comment]
ทดสอบ POST รายละเอียดดังนี้

- Path: `{{url}}/org/{{org_id}}/user`
- Authorization : Type OAuth 2.0 Access Token ใช้ `{{org_token}}`
- ด้วย Body ตามด้านล่างนี้ 

`[
  {
    "name": "blast",
    "password": "theblast",
    "role": "USER",
    "id": "1238c14b3feb47dba0311cf6dd8233a6",
    "type": "User",
    "timestamp": "2018-06-28T14:14:43.645+07:00"
  },
  {
    "name": "max",
    "password": "maxmax",
    "role": "USER",
    "id": "456194a5b85b4733889247578e4bd5f0",
    "type": "User",
    "timestamp": "2018-06-28T14:19:29.645+07:00"
  },
  {
    "name": "ploy",
    "password": "n",
    "role": "USER",
    "id": "789194a5b85b4733889247578e4bd5f0",
    "type": "User",
    "timestamp": "2018-06-28T14:30:29.645+07:00"
  }
]`
